### ISSUE TITLE
Won't work with 6.x due to rename

### ISSUE THREAD

**Issue by dgw** [dgw/willie-UnoBot#18]
Module needs to import from "sopel" instead of "willie" for 6.x compatibility (the rename that didn't need to happen, happened anyway).
- [x] Change imports from `willie` to import from `sopel`
- [ ] Try to import `sopel` packages first and fall back to `willie` if needed
- [x] Rename repository

Screwing with the imports might be unnecessary if @embolalia pushes a shim to make both `willie` and `sopel` imports work with future versions, as is possibly planned. But it's good to have on the radar.

**Comment by embolalia** [comment]
I've added the ability to import from `sopel` to the [5.x branch](https://github.com/sopel-irc/sopel/tree/5.x). I've only done a little testing with it, but it seems to work. I'll be making a 5.5 release with that within a few days. The ability to import from `willie` will not be added to 6.0.

Same goes for dgw/willie-BombBot#8.

**Comment by dgw** [comment]
Ugh, force pushing.

Leaving open for now as I'm not really sure the try-sopel-then-try-willie import logic is worth adding… Will think on it.

**Comment by dgw** [comment]
Thought on it. Not going to bother with fallback imports.
