### ISSUE TITLE
Error loading Unobot

### ISSUE THREAD

**Issue by dasu** [dgw/willie-UnoBot#44]
Error loading unobot: invalid syntax (unobot.py, line 697)  
Grabbed the very latest commit as of today.
I'm on python3.3.  Not sure if i'm missing any potential requirements.

**Comment by dgw** [comment]
Hmm… I may need to look into handling exceptions under 2.x vs 3.x. My instance is on 2.7 and doesn't throw syntax errors for that code. (Score saving error handling in general is also the least well tested bit of code, so…)

I'm out of town, so this may take a couple of weeks to track down depending on how my schedule works out. But I appreciate the report :)

**Comment by dgw** [comment]
Yep, there are five (by my quick count) spots using `except` syntax that was removed in Python 3. I'll let you know when I get a chance to push up a branch with tentative fixes so you can test it. Probably sometime between now and the end of the week. Doubt it'll take me more than an hour with my laptop, once I find time to sit down and do it.

**Comment by dgw** [comment]
Finally found a moment for this. @dasu, can you try the [py3-exception-syntax](https://github.com/dgw/sopel-UnoBot/tree/py3-exception-syntax) branch?

**Comment by dasu** [comment]
I haven't tested it yet but I know it'll fail because of the print at the end.  It'll work thought since I made the same changes as you.

**Comment by dgw** [comment]
Ugh, I left that `print` in when I adopted the code, for no particular reason. I should just carve out an evening (or whatever) and make sure the whole module is compatible with both py2.7 and py3. Thanks for the nudge, though. Knowing people are running this on both gives me reason to check compatibility going forward.

**Comment by dgw** [comment]
Closing in favor of #46 as a tracking issue.
